[versions]
kotlin = "1.9.21"
agp = "8.11.1"

## SDK Versions
minSdk = "26"
targetSdk = "34"
compileSdk = "34"

# Dependencies
ktlint-gradle = "11.2.0"
gradle-versions = "0.42.0"

compose = "1.6.0"
compose-compiler = "1.5.8"
compose-plugin = "1.5.11"

android-desugaring = "2.1.5"
androidx-core = "1.12.0"
androidx-test-junit = "1.1.5"
androidx-activity-compose = "1.8.2"
androidx-lifecycle = "2.7.0"
androidx-material3 = "1.1.2"
androidx-camera = "1.4.1"

junit = "4.13.2"
ksp = "2.1.21-2.0.1"
mockmp = "2.0.2"

coroutines = "1.7.3"
kotlinx-datetime = "0.4.0"
ktor = "2.1.1"

kermit = "1.2.2"
stately = "1.2.3"

koin = "3.2.0"
multiplatformSettings = "1.0.0"
sqlDelight = "1.5.5"
moko-mvvm = "0.16.1"
moko-resources = "0.23.0"
moko-kswift = "0.7.0"
composeSettings = "2.1.0"

[libraries]
android-desugaring = { module = "com.android.tools:desugar_jdk_libs", version.ref = "android-desugaring" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.7.1" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "androidx-material3" }
androidx-material3-windowsize = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "androidx-material3" }
androidx-test-junit = { module = "androidx.test.ext:junit-ktx", version.ref = "androidx-test-junit" }
androidx-datastore = { module = "androidx.datastore:datastore-preferences", version = "1.0.0" }
androidx-splashscreen = { module = "androidx.core:core-splashscreen", version = "1.0.1" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version = "2.8.5" }
androidx-camera-core = { module = "androidx.camera:camera-core", version.ref = "androidx-camera" }
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "androidx-camera" }
androidx-camera-view = { module = "androidx.camera:camera-view", version.ref = "androidx-camera" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "androidx-camera" }
androidx-exifinterface = { module = "androidx.exifinterface:exifinterface", version = "1.4.1" }

compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "compose-compiler" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-viewbinding = { module = "androidx.compose.ui:ui-viewbinding", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity-compose" }

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

google-accompanist-themeadapter-appcompat = { module = "com.google.accompanist:accompanist-themeadapter-appcompat", version = "0.36.0" }
google-accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version = "0.37.3" }

junit = { module = "junit:junit", version.ref = "junit" }

koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }

kotlinx-dateTime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-ios = { module = "io.ktor:ktor-client-ios", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-okHttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-serialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-contentNegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }

multiplatformSettings-common = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatformSettings" }
multiplatformSettings-test = { module = "com.russhwolf:multiplatform-settings-test", version.ref = "multiplatformSettings" }
multiplatformSettings-coroutines = { module = "com.russhwolf:multiplatform-settings-coroutines", version.ref = "multiplatformSettings" }
multiplatformSettings-datastore = { module = "com.russhwolf:multiplatform-settings-datastore", version.ref = "multiplatformSettings" }

resources-generator = { module = "dev.icerock.moko:resources-generator", version.ref = "moko-resources" }

sqlDelight-android = { module = "com.squareup.sqldelight:android-driver", version.ref = "sqlDelight" }
sqlDelight-jvm = { module = "com.squareup.sqldelight:sqlite-driver", version.ref = "sqlDelight" }
sqlDelight-coroutinesExt = { module = "com.squareup.sqldelight:coroutines-extensions", version.ref = "sqlDelight" }
sqlDelight-native = { module = "com.squareup.sqldelight:native-driver", version.ref = "sqlDelight" }
sqlDelight-runtime = { module = "com.squareup.sqldelight:runtime", version.ref = "sqlDelight" }

touchlab-kermit = { module = "co.touchlab:kermit", version = "1.2.3" }
touchlab-stately = { module = "co.touchlab:stately-common", version = "1.2.5" }

moko-mvvm-core = { module = "dev.icerock.moko:mvvm-core", version.ref = "moko-mvvm" }
moko-mvvm-flow = { module = "dev.icerock.moko:mvvm-flow", version.ref = "moko-mvvm" }
moko-mvvm-flow-compose = { module = "dev.icerock.moko:mvvm-flow-compose", version.ref = "moko-mvvm" }
moko-mvvm-livedata = { module = "dev.icerock.moko:mvvm-livedata", version.ref = "moko-mvvm" }
moko-mvvm-state = { module = "dev.icerock.moko:mvvm-state", version.ref = "moko-mvvm" }
moko-mvvm-livedata-resources = { module = "dev.icerock.moko:mvvm-livedata-resources", version.ref = "moko-mvvm" }
moko-mvvm-test = { module = "dev.icerock.moko:mvvm-test", version.ref = "moko-mvvm" }
moko-mvvm-android-livedata-compose = { module = "dev.icerock.moko:mvvm-livedata-compose", version.ref = "moko-mvvm" }

moko-resources = { module = "dev.icerock.moko:resources", version.ref = "moko-resources" }
moko-resources-compose = { module = "dev.icerock.moko:resources-compose", version.ref = "moko-resources" }
moko-resources-test = { module = "dev.icerock.moko:resources-test", version.ref = "moko-resources" }

moko-kswift-gradle-plugin = { module = "dev.icerock.moko:kswift-gradle-plugin", version.ref = "moko-kswift" }
moko-kswift-runtime = { module = "dev.icerock.moko:kswift-runtime", version.ref = "moko-kswift" }

turbine = { module = "app.cash.turbine:turbine", version = "1.2.1" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
coil = { module = "io.coil-kt:coil-compose", version = "2.7.0" }
ksoup-entities = { module = "com.mohamedrejeb.ksoup:ksoup-entities", version = "0.3.1" }
compose-settings = { module = "com.github.alorma.compose-settings:ui-tiles", version.ref = "composeSettings" }
compose-settings-extended = { module = "com.github.alorma.compose-settings:ui-tiles-extended", version.ref = "composeSettings" }
compose-webview = { module = "io.github.kevinnzou:compose-webview", version = "0.33.6" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
gradleVersions = { id = "com.github.ben-manes.versions", version.ref = "gradle-versions" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-gradle" }
sqlDelight = { id = "com.squareup.sqldelight", version.ref = "sqlDelight" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
mockmp = { id = "org.kodein.mock.mockmp", version.ref = "mockmp" }

[bundles]
app-ui = [
    "compose-compiler",
    "androidx-core",
    "androidx-lifecycle-runtime-compose",
    "androidx-lifecycle-viewmodel-compose",
    "androidx-appcompat",
    "androidx-material3",
    "androidx-material3-windowsize",
    "androidx-datastore",
    "androidx-splashscreen",
    "androidx-navigation-compose",
    "androidx-camera-core",
    "androidx-camera-camera2",
    "androidx-camera-view",
    "androidx-camera-lifecycle",
    "androidx-exifinterface",
    "compose-ui",
    "compose-ui-viewbinding",
    "compose-ui-tooling",
    "compose-foundation",
    "compose-activity",
    "compose-webview",
    "google-accompanist-themeadapter-appcompat",
    "google-accompanist-permissions",
    "compose-settings",
    "compose-settings-extended"
]
ktor-common = [
    "ktor-client-core",
    "ktor-client-logging",
    "ktor-client-serialization",
    "ktor-client-contentNegotiation",
    "ktor-client-auth"
]
moko-mvvm-common = [
    "moko-mvvm-core",
    "moko-mvvm-flow",
    "moko-mvvm-livedata"
]
moko-resources-common = [
    "moko-resources",
    "moko-resources-compose"
]
shared-commonTest = [
    "kotlin-test",
    "multiplatformSettings-test",
    "koin-test",
    "turbine",
    "coroutines-test",
    "ktor-client-mock",
    "moko-mvvm-test",
    "moko-resources-test"
]
shared-androidTest = [
    "androidx-test-junit",
    "coroutines-test",
    "sqlDelight-jvm"
]